name: bubble
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore:
  dartz:
  freezed_annotation:
  firebase_messaging:
  shared_preferences:
  firebase_auth:
  camera:
  flutter_keyboard_visibility:
  cached_network_image:
  path_provider:
  path:
  firebase_database:
  photo_view:
  auto_route:
  firebase_storage:
  google_sign_in:
  flutter_local_notifications:
  injectable:
  flutter_bloc:
  flutter_material_color_picker:
  dashed_circle:
  image_picker:
  flutter_svg:
  flutter_native_image:
  transparent_image:
  flutter_clipboard_manager:
  fluttertoast:
  get_it:

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner:
  freezed:
  injectable_generator:
  auto_route_generator:
  lint: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon.svg
    - assets/images/bubble.svg
    - assets/images/welcome.svg
    - assets/images/congrats.svg
    - assets/images/theme.svg
    - assets/images/img_not_available.jpeg
    - assets/images/like.svg
    - assets/images/font.svg
    - assets/images/more.svg
    - assets/images/money.svg
    - assets/images/poo.svg
    - assets/images/flower.svg
    - assets/images/rose.svg
    - assets/images/fire.svg
    - assets/images/waving-hand.svg
    - assets/images/color-wheel.svg
    - assets/images/logout.svg
    - assets/images/heart.svg
    - assets/stickers/mimi1.gif
    - assets/stickers/mimi2.gif
    - assets/stickers/mimi4.gif
    - assets/stickers/mimi5.gif
    - assets/stickers/mimi6.gif
    - assets/stickers/mimi7.gif
    - assets/stickers/mimi8.gif
    - assets/stickers/mimi9.gif
    - assets/stickers/giphy (1)-min.gif
    - assets/stickers/giphy (2)-min.gif
    - assets/stickers/giphy (3)-min.gif
    - assets/stickers/giphy (4)-min.gif
    - assets/stickers/giphy (5)-min.gif
    - assets/stickers/giphy (6)-min.gif
    - assets/stickers/giphy (7)-min.gif
    - assets/stickers/giphy (8)-min.gif
    - assets/stickers/giphy (9)-min.gif
    - assets/stickers/giphy (10)-min.gif
    - assets/stickers/giphy (11)-min.gif
    - assets/stickers/giphy (12)-min.gif
    - assets/stickers/giphy (13)-min.gif
    - assets/stickers/giphy (14)-min.gif
    - assets/stickers/giphy (15)-min.gif
    - assets/stickers/giphy (16)-min.gif
    - assets/stickers/giphy (17)-min.gif
    - assets/stickers/giphy (18)-min.gif
    - assets/stickers/giphy (19)-min.gif
    - assets/stickers/giphy (20)-min.gif
    - assets/stickers/giphy (21)-min.gif
    - assets/stickers/giphy (22)-min.gif
    - assets/stickers/giphy (23)-min.gif
    - assets/stickers/giphy (24)-min.gif
    - assets/stickers/giphy (25)-min.gif
    - assets/stickers/giphy (26)-min.gif
    - assets/stickers/giphy (27)-min.gif
    - assets/stickers/giphy (28)-min.gif
    - assets/stickers/giphy (29)-min.gif
    - assets/stickers/giphy (30)-min.gif
    - assets/stickers/giphy (31)-min.gif
    - assets/stickers/giphy (32)-min.gif
    - assets/stickers/giphy (33)-min.gif
    - assets/stickers/giphy (34)-min.gif
    - assets/stickers/giphy (35)-min.gif
    - assets/stickers/giphy (36)-min.gif
    - assets/stickers/giphy (37)-min.gif
    - assets/stickers/giphy (38)-min.gif
    - assets/stickers/giphy (39)-min.gif
    - assets/stickers/giphy (40)-min.gif
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Paprika
      fonts:
        - asset: assets/fonts/Paprika-Regular.ttf
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
