const List<String> stickers = [
  "giphy (1)-min",
  "giphy (2)-min",
  "giphy (3)-min",
  "giphy (4)-min",
  "giphy (5)-min",
  "giphy (6)-min",
  "giphy (7)-min",
  "giphy (8)-min",
  "giphy (9)-min",
  "giphy (10)-min",
  "giphy (11)-min",
  "giphy (12)-min",
  "giphy (13)-min",
  "giphy (14)-min",
  "giphy (15)-min",
  "giphy (16)-min",
  "giphy (17)-min",
  "giphy (18)-min",
  "giphy (19)-min",
  "giphy (20)-min",
  "giphy (21)-min",
  "giphy (22)-min",
  "giphy (23)-min",
  "giphy (24)-min",
  "giphy (25)-min",
  "giphy (26)-min",
  "giphy (27)-min",
  "giphy (28)-min",
  "giphy (29)-min",
  "giphy (30)-min",
  "giphy (31)-min",
  "giphy (32)-min",
  "giphy (33)-min",
  "giphy (34)-min",
  "giphy (35)-min",
  "giphy (36)-min",
  "giphy (37)-min",
  "giphy (38)-min",
  "giphy (39)-min",
  "giphy (40)-min",
  "mimi1",
  "mimi2",
  "mimi4",
  "mimi5",
  "mimi6",
  "mimi7",
  "mimi8",
  "mimi9"
];
